Olympics 2021 anaylsis

Group:-
1.   265 Tuhinansh Sharma
2.   266 Tushar Najawan
3.    279 Atharva Pawar

In [ ]:
import pandas as pd


df = pd.read_csv('/content/Tokyo 2021 dataset v4.csv')
df

In [ ]:
# 1. Display the first 5 rows
print("Query 1:")
print(df.head())

In [ ]:
# 2. Display the last 5 rows
print("Query 2:")
print(df.tail())

In [ ]:
# 3. Display the total number of rows and columns
print("Query 3:")
print(df.shape)

In [ ]:
# 4. Display the column names
print("Query 4:")
print(df.columns)

In [ ]:
# 5. Display the gold medal count for the United States
print("Query 5:")
print(df[df['Team/NOC'] == 'United States of America']['Gold Medal'])

In [ ]:
# 6. Display the countries with more than 30 gold medals
print("Query 6:")
print(df[df['Gold Medal'] > 30]['Team/NOC'])

In [ ]:
# 7. Display the countries in Europe
print("Query 7:")
print(df[df['Continent'] == 'Europe']['Team/NOC'])

In [ ]:
# 8. Display the top 5 countries with the highest total medal count
print("Query 8:")
print(df.nlargest(5, 'Total')[['Team/NOC', 'Total']])

In [ ]:
# 9. Display the countries with no gold medals
print("Query 9:")
print(df[df['Gold Medal'] == 0]['Team/NOC'])

In [ ]:
# 10. Display the countries with more silver medals than bronze medals
print("Query 10:")
print(df[df['Silver Medal'] > df['Bronze Medal']]['Team/NOC'])

Groupby function

In [ ]:
# 11. Display the continents and their respective total medal count
print("Query 11:")
print(df.groupby('Continent')['Total'].sum())

In [ ]:
# 12. Display the average number of medals per country
print("Query 12:")
print(df[['Gold Medal', 'Silver Medal', 'Bronze Medal']].mean())

In [ ]:
# 13. Display the countries with a gold medal count between 5 and 10 (inclusive)
print("Query 13:")
print(df[(df['Gold Medal'] >= 5) & (df['Gold Medal'] <= 10)]['Team/NOC'])

In [ ]:
# 14. Display the top 3 countries with the highest silver medal count
print("Query 14:")
print(df.nlargest(3, 'Silver Medal')[['Team/NOC', 'Silver Medal']])

In [ ]:
# 15. Display the countries with a total medal count of 0
print("Query 15:")
print(df[df['Total'] == 0]['Team/NOC'])

In [ ]:
# 16. Display the countries with more gold medals than any other medal
print("Query 16:")
print(df[(df['Gold Medal'] > df['Silver Medal']) & (df['Gold Medal'] > df['Bronze Medal'])]['Team/NOC'])

In [ ]:
# 17. Display the countries with a total medal count greater than or equal to 50
print("Query 17:")
print(df[df['Total'] >= 50]['Team/NOC'])

In [ ]:
# 18. Display the countries in Asia with a bronze medal count greater than 5
print("Query 18:")
print(df[(df['Continent'] == 'Asia') & (df['Bronze Medal'] > 5)]['Team/NOC'])

In [ ]:
# 19. Display the top 5 countries with the highest gold-to-total medal ratio
print("Query 19:")
df['Gold/Total Ratio'] = df['Gold Medal'] / df['Total']
print(df.nlargest(5, 'Gold/Total Ratio')[['Team/NOC', 'Gold/Total Ratio']])

In [ ]:
#20. Total no. of gold medals
print("Query 20:")
gold_medal_count = df['Gold Medal'].count()
print("Gold Medal Count:", gold_medal_count)