In [2]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/Tokyo 2021 dataset v4.csv')

In [ ]:
# 1. Display the first 5 rows
print("Query 1:")
print(df.head())

In [ ]:
# 2. Display the last 5 rows
print("Query 2:")
print(df.tail())

In [5]:
# 3. Display the total number of rows and columns
print("Query 3:")
print(df.shape)

Query 3:
(93, 9)

In [6]:
# 4. Display the column names
print("Query 4:")
print(df.columns)

Query 4:
Index(['Rank', 'Team/NOC', 'Gold Medal', 'Silver Medal', 'Bronze Medal',
       'Total', 'Rank by Total', 'NOCCode', 'Continent'],
      dtype='object')

In [7]:
# 5. Display the gold medal count for the United States
print("Query 5:")
print(df[df['Team/NOC'] == 'United States of America']['Gold Medal'])

Query 5:
0    39
Name: Gold Medal, dtype: int64

In [8]:
# 6. Display the countries with more than 30 gold medals
print("Query 6:")
print(df[df['Gold Medal'] > 30]['Team/NOC'])

Query 6:
0      United States of America
1    People's Republic of China
Name: Team/NOC, dtype: object

In [ ]:
# 7. Display the countries in Europe
print("Query 7:")
print(df[df['Continent'] == 'Europe']['Team/NOC'])

In [11]:
# 8. Display the top 5 countries with the highest total medal count
print("Query 8:")
print(df.nlargest(5, 'Total')[['Team/NOC', 'Total']])

Query 8:
                     Team/NOC  Total
0    United States of America    113
1  People's Republic of China     88
4                         ROC     71
3               Great Britain     65
2                       Japan     58

In [ ]:
# 9. Display the countries with no gold medals
print("Query 9:")
print(df[df['Gold Medal'] == 0]['Team/NOC'])

In [ ]:
# 10. Display the countries with more silver medals than bronze medals
print("Query 10:")
print(df[df['Silver Medal'] > df['Bronze Medal']]['Team/NOC'])

In [14]:
# 11. Display the continents and their respective total medal count
print("Query 11:")
print(df.groupby('Continent')['Total'].sum())

Query 11:
Continent
Africa            38
Asia             237
Australia         68
Europe           455
Europe/Asia       71
North America    175
South America     36
Name: Total, dtype: int64

In [15]:
# 12. Display the average number of medals per country
print("Query 12:")
print(df[['Gold Medal', 'Silver Medal', 'Bronze Medal']].mean())

Query 12:
Gold Medal      3.655914
Silver Medal    3.634409
Bronze Medal    4.322581
dtype: float64

In [16]:
# 13. Display the countries with a gold medal count between 5 and 10 (inclusive)
print("Query 13:")
print(df[(df['Gold Medal'] >= 5) & (df['Gold Medal'] <= 10)]['Team/NOC'])

Query 13:
6           Netherlands
7                France
8               Germany
9                 Italy
10               Canada
11               Brazil
12          New Zealand
13                 Cuba
14              Hungary
15    Republic of Korea
Name: Team/NOC, dtype: object

In [17]:
# 14. Display the top 3 countries with the highest silver medal count
print("Query 14:")
print(df.nlargest(3, 'Silver Medal')[['Team/NOC', 'Silver Medal']])

Query 14:
                     Team/NOC  Silver Medal
0    United States of America            41
1  People's Republic of China            32
4                         ROC            28

In [18]:
# 15. Display the countries with a total medal count of 0
print("Query 15:")
print(df[df['Total'] == 0]['Team/NOC'])

Query 15:
Series([], Name: Team/NOC, dtype: object)

In [ ]:
# 16. Display the countries with more gold medals than any other medal
print("Query 16:")
print(df[(df['Gold Medal'] > df['Silver Medal']) & (df['Gold Medal'] > df['Bronze Medal'])]['Team/NOC'])

In [20]:
# 17. Display the countries with a total medal count greater than or equal to 50
print("Query 17:")
print(df[df['Total'] >= 50]['Team/NOC'])

Query 17:
0      United States of America
1    People's Republic of China
2                         Japan
3                 Great Britain
4                           ROC
Name: Team/NOC, dtype: object

In [21]:
# 18. Display the countries in Asia with a bronze medal count greater than 5
print("Query 18:")
print(df[(df['Continent'] == 'Asia') & (df['Bronze Medal'] > 5)]['Team/NOC'])

Query 18:
1     People's Republic of China
2                          Japan
15             Republic of Korea
33                Chinese Taipei
Name: Team/NOC, dtype: object

In [22]:
# 19. Display the top 5 countries with the highest gold-to-total medal ratio
print("Query 19:")
df['Gold/Total Ratio'] = df['Gold Medal'] / df['Total']
print(df.nlargest(5, 'Gold/Total Ratio')[['Team/NOC', 'Gold/Total Ratio']])

Query 19:
       Team/NOC  Gold/Total Ratio
41      Bahamas               1.0
42       Kosovo               1.0
62      Bermuda               1.0
63      Morocco               1.0
64  Puerto Rico               1.0

In [23]:
# 20. Display the countries with a gold medal count greater than the silver and bronze medal count combined
print("Query 20:")
df['Silver+Bronze'] = df['Silver Medal'] + df['Bronze Medal']
print(df[df['Gold Medal'] > df['Silver+Bronze']]['Team/NOC'])

Query 20:
30       Slovenia
31     Uzbekistan
37        Ecuador
40          Qatar
41        Bahamas
42         Kosovo
62        Bermuda
63        Morocco
64    Puerto Rico
Name: Team/NOC, dtype: object