In [6]:
import csv
f1=open("/content/employwe.csv",'r')
f2=open("/content/employwe2.csv",'r')
f3=open("/content/merge1.csv",'w')

data1=list(csv.reader(f1, delimiter=","))
data2=list(csv.reader(f2, delimiter=","))

print('The employee contains are',data1)
print('The job title of employee are',data2)

data3=[]
for i in range(len(data2)):
  data3.append(data1[i]+data2[i])
  cf3=csv.writer(f3)
print('\nThe merged file is',data3)

sal=[]
for i in range(1,len(data1)):
   if len(l) != 0 :
   # print(len(l))
    sal.append(int(data1[i][3]))
print('The salary data is')
for i in sal:
  print(i)
sum=0
for i in sal:
  sum=sum+i

print('The avg salary is',sum/len(sal))
print('The max salary is',max(sal))
print('The min salary is',min(sal))

def top3emp(data3):
  data3.sort(key=lambda x: (x[5]), reverse=True)
  print("\ntop 3 records are:-")
  for i in range(3):
    print(data3[i+1][3])
top3emp(data3)

from datetime import data
print(data.today())
2023/5/3
f1.close()
f2.close()
f3.close()

The employee contains are [['Rohit', '320000', '5/2/1992'], ['Mayank', '590000', '16/9/1975'], ['Sampat', '450000', '25/7/1974'], ['Daulat', '900000', '23/8/1979'], ['Sangram', '1000000', '4/3/1970'], ['Aryaa', '2000000', '2/9/1980']]
The job title of employee are [['Rohit', 'Manager'], ['Mayank', 'scientist'], ['Sampat', 'accountant'], ['Daulat', 'HR'], ['Sangram', "Sale's Manager"], ['Aryaa', 'Chairman']]

The merged file is [['Rohit', '320000', '5/2/1992', 'Rohit', 'Manager'], ['Mayank', '590000', '16/9/1975', 'Mayank', 'scientist'], ['Sampat', '450000', '25/7/1974', 'Sampat', 'accountant'], ['Daulat', '900000', '23/8/1979', 'Daulat', 'HR'], ['Sangram', '1000000', '4/3/1970', 'Sangram', "Sale's Manager"], ['Aryaa', '2000000', '2/9/1980', 'Aryaa', 'Chairman']]

NameError: ignored